In [12]:

import numpy as np  
import scipy as sp  
from sklearn import tree  
from sklearn.metrics import precision_recall_curve  
from sklearn.metrics import classification_report  
from sklearn.cross_validation import train_test_split  

import  xdrlib ,sys
import xlrd

#保证可以使用中文字符



In [13]:
''' 数据读入 '''
data = []
labels = []
yiliaodata = xlrd.open_workbook('yiliaodata _all.xlsx')
table = yiliaodata.sheets()[0]
nrows = table.nrows #行数
ncols = table.ncols #列数
colnames =  table.row_values(0) #某一行数据
print colnames

print "*********"
for rownum in range(1,nrows):
    row = table.row_values(rownum)
    data.append([float(tk) for tk in row[:-1]])
    labels.append(row[-1])
print data
print '************'
print labels

[u'item1', u'item2', u'item3', u'item4', u'item5', u'item6', u'result']
*********
[[2.52208354728958, 9.91206550335961, 5.47372058083004, 9.7089241416475, 3.05577662877431, 3.37999481667522], [7.85888314623779, 7.72286538809941, 6.13709246873177, 5.41469951555313, 4.31639438374654, 5.1414318793308], [0.116719163592149, 5.27644624571159, 0.900901898616778, 6.57749598349704, 4.37900814874969, 2.07529934131481], [1.91300805276933, 7.98633351475754, 3.78609490070865, 8.89931808628207, 0.909737136632764, 6.28341338909567], [4.92330344564285, 2.8894128362053, 9.93802399316999, 2.14568575739221, 2.63089980993867, 7.89447804736992], [8.0946616930892, 1.37410957045307, 4.54126147170799, 0.369286594156857, 2.82107781392357, 0.773171474040563], [0.856271680996312, 5.49740692995576, 0.261042114264456, 1.71165693903517, 7.14115851286244, 7.0535097643431], [9.45433008652537, 9.76373083811009, 9.87130778564143, 5.7054057249968, 4.95813825956434, 8.0233877659632], [0.212186055755443, 5.00995781217216,

In [14]:
stdi,stdo,stde=sys.stdin,sys.stdout,sys.stderr
import sys
reload(sys)
sys.stdin,sys.stdout,sys.stderr=stdi,stdo,stde
sys.setdefaultencoding('utf-8')


x = np.array(data)
labels = np.array(labels)
y = np.zeros(labels.shape)

''' 标签转换为0/1 '''
y[labels=='正'] = 1
y

array([ 0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,
        1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        0.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,
        0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,
        0.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,
        0.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,
        0.,  1.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,
        0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,
        0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,
        1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1

In [15]:
''' 拆分训练数据与测试数据 '''
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [16]:
''' 使用信息熵作为划分标准，对决策树进行训练 '''
clf = tree.DecisionTreeClassifier(criterion='entropy')
print(clf)
clf.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')


DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [17]:
''' 把决策树结构写入文件 '''
with open("tree_yiliao.dot", 'w') as f:
    f = tree.export_graphviz(clf, out_file=f)

In [18]:
''' 系数反映每个特征的影响力。越大表示该特征在分类中起到的作用越大 '''
print(clf.feature_importances_)

[ 0.53992399  0.19212664  0.19299964  0.04005174  0.02371259  0.0111854 ]


In [19]:
'''测试结果的打印'''
answer = clf.predict(x_train)
print(x_train)
print(answer)
print(y_train)
print(np.mean( answer == y_train))

[[ 0.77961545  2.1155919   5.08594384  0.6270265   8.10285869  2.86253623]
 [ 6.26032577  5.47388186  5.02469078  9.75724647  0.44635523  8.93891436]
 [ 0.16928581  7.21584144  2.0806644   6.36071806  4.62393942  6.58089966]
 ..., 
 [ 2.52121537  0.35098403  5.3983413   7.67414307  1.28010084  9.11994358]
 [ 9.13253533  9.17486708  3.42443951  8.67916447  2.80834402  1.78628458]
 [ 2.19024927  4.72611729  9.15700167  4.55320434  5.46655225  6.77982262]]
[ 0.  1.  0.  1.  1.  1.  1.  1.  1.  0.  1.  0.  0.  1.  0.  1.  0.  1.
  1.  1.  0.  0.  1.  0.  0.  0.  0.  1.  1.  1.  1.  0.  1.  0.  1.  0.
  1.  1.  1.  0.  1.  1.  1.  0.  1.  0.  0.  0.  1.  1.  1.  0.  0.  1.
  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  1.  1.  0.  1.  1.  0.  0.  0.
  0.  0.  0.  1.  1.  0.  0.  1.  1.  0.  1.  1.  0.  1.  1.  0.  1.  0.
  0.  1.  1.  1.  1.  0.  1.  0.  1.  1.  1.  0.  0.  1.  0.  0.  1.  1.
  1.  0.  1.  1.  0.  1.  0.  0.  0.  0.  1.  1.  0.  1.  0.  1.  1.  1.
  0.  1.  0.  0.  1.  0.  1.  1

In [20]:
'''准确率与召回率'''
precision, recall, thresholds = precision_recall_curve(y_train, clf.predict(x_train))
answer = clf.predict_proba(x)[:,1]
print(classification_report(y, answer, target_names = ['正', '负']))

             precision    recall  f1-score   support

        正       0.98      0.96      0.97       238
        负       0.97      0.98      0.98       262

avg / total       0.97      0.97      0.97       500

